/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretSlugRouteImport } from './routes/secret.$slug'
import { Route as RevealSlugRouteImport } from './routes/reveal.$slug'
import { Route as AuthenticatedDreamRouteImport } from './routes/_authenticated/dream'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretSlugRoute = SecretSlugRouteImport.update({
  id: '/secret/$slug',
  path: '/secret/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealSlugRoute = RevealSlugRouteImport.update({
  id: '/reveal/$slug',
  path: '/reveal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDreamRoute = AuthenticatedDreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dream': typeof AuthenticatedDreamRoute
  '/reveal/$slug': typeof RevealSlugRoute
  '/secret/$slug': typeof SecretSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dream': typeof AuthenticatedDreamRoute
  '/reveal/$slug': typeof RevealSlugRoute
  '/secret/$slug': typeof SecretSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chapters': typeof ChaptersRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dream': typeof AuthenticatedDreamRoute
  '/reveal/$slug': typeof RevealSlugRoute
  '/secret/$slug': typeof SecretSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chapters'
    | '/progress'
    | '/admin'
    | '/dream'
    | '/reveal/$slug'
    | '/secret/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chapters'
    | '/progress'
    | '/admin'
    | '/dream'
    | '/reveal/$slug'
    | '/secret/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chapters'
    | '/progress'
    | '/_authenticated/admin'
    | '/_authenticated/dream'
    | '/reveal/$slug'
    | '/secret/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChaptersRoute: typeof ChaptersRoute
  ProgressRoute: typeof ProgressRoute
  RevealSlugRoute: typeof RevealSlugRoute
  SecretSlugRoute: typeof SecretSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secret/$slug': {
      id: '/secret/$slug'
      path: '/secret/$slug'
      fullPath: '/secret/$slug'
      preLoaderRoute: typeof SecretSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal/$slug': {
      id: '/reveal/$slug'
      path: '/reveal/$slug'
      fullPath: '/reveal/$slug'
      preLoaderRoute: typeof RevealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dream': {
      id: '/_authenticated/dream'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof AuthenticatedDreamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDreamRoute: typeof AuthenticatedDreamRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDreamRoute: AuthenticatedDreamRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChaptersRoute: ChaptersRoute,
  ProgressRoute: ProgressRoute,
  RevealSlugRoute: RevealSlugRoute,
  SecretSlugRoute: SecretSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
